### ISSUE TITLE
working of the validator

### ISSUE THREAD

**Issue by Anu-Ra-g** [gerald1248/validate-yaml#1]
@gerald1248  Does the validator work only when you validate the yaml file against an equivalent JSON file?
![Screenshot (834)](https://github.com/gerald1248/validate-yaml/assets/94440065/14a78df4-266f-4a09-a0c9-86273b900f9a)

**Comment by gerald1248** [comment]
> Does the validator work only when you validate the yaml file against an equivalent JSON file?
No. It should accept YAML or JSON for both schema and instance document.

**Comment by Anu-Ra-g** [comment]
@gerald1248 No, I meant to ask what is the yaml validated against? A equivalent json file?
![Screenshot (835)](https://github.com/gerald1248/validate-yaml/assets/94440065/600df703-82e7-4348-8e47-55fd49ae8bc9)
![Screenshot (836)](https://github.com/gerald1248/validate-yaml/assets/94440065/0ac5ef28-9874-46e0-a4f7-ea15ae70207f)

**Comment by gerald1248** [comment]
Ah not quite! The schema is expressed as JSON Schema, which can be
presented as JSON or YAML. It’s a great schema language! There are some
examples in the testdata folder.

**Comment by gerald1248** [comment]
See
https://json-schema.org/

**Comment by Anu-Ra-g** [comment]
@gerald1248 Thanks for the help
